# Generated by Django 3.0 on 2019-12-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('host_name', models.TextField()),
                ('neighbourhood_group', models.TextField()),
                ('neighbourhood', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('room_type', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
